const VEHICLE_TYPE = {
  OFFICIAL: 'OFFICIAL',
  RESIDENT: 'RESIDENT',
  NON_RESIDENT: 'NON_RESIDENT'
}

const DB_PROVIDER = {
  MYSQL: 'mysql',
  POSTGRES: 'postgres'
}

const STAY_TAXES = {
  [VEHICLE_TYPE.RESIDENT]: 0.05,
  [VEHICLE_TYPE.NON_RESIDENT]: 0.5
}

module.exports = {
  VEHICLE_TYPE,
  DB_PROVIDER,
  STAY_TAXES
}